### ISSUE TITLE
Chroma Key IP core

### ISSUE THREAD

**Issue by MalavPatel3501** [bunnie/netv2-fpga-chroma-key#1]
Please Provide More Detail to how to use Chroma Key IP.

**Comment by bunnie** [comment]
Please refer to alphamxmedia for support on this issue, and the official wiki page:

https://github.com/AlphamaxMedia/netv2-fpga/wiki/Customizing-Chroma-and-Colorspace

If the page does not give enough details, please open an issue here

https://github.com/AlphamaxMedia/netv2-fpga/issues

with the specifics of what you need support on. I'll close this here, because this is not the correct repo for support questions.
